services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: mvp_db
      POSTGRES_USER: knovadev
      POSTGRES_PASSWORD: knovadevpass
    ports:
      - "5436:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: